### ISSUE TITLE
中文手写字体未生效

### ISSUE THREAD

**Issue by imx7** [jcyh0120/excalidraw-custom-font#2]
按照操作步骤，没有生效。
本地docker-compose部署的：excalidraw/excalidraw:latest
url是https://github.com/max32002/JasonHandWritingFonts/blob/master/webfont/JasonHandwriting5p.woff2
本地有VPN，可以访问到URL
点击changfont后，等待3-10秒（均测试过），然后切换深色/浅色，中文字体还是原来的样子，没有变成手写的。

**Comment by imx7** [comment]
OS is windows,should be macos

**Comment by lflys** [comment]
Encountered a CORS (Cross-Origin Resource Sharing) policy error when I trying to access a font hosted on GitHub:
> Access to font at 'https://github.com/max32002/JasonHandWritingFonts/raw/master/webfont/JasonHandwriting1-Regular.woff2' from origin 'https://excalidraw.com' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'https://render.githubusercontent.com' that is not equal to the supplied origin.

Using links from sources other than GitHub can resolve this issue.
